#stage 1 : Build Docker Image and Publish
#Build Docker Image
#Stage2
#Get K8s Deployment config File from code path
#Deploy to K8s cluster

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push to Image
      inputs:
        containerRegistry: 'svcconn-dockerhub'
        repository: 'snayakwadi41/currency-exchange'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'S(Build.ArtifactStagingDirectory'
        ArtifactName: manifests
        publishLocation: Container

- stage: 
  displayName: DownloadAndDeploy
  jobs:
  - job: DownloadArtifacts
    displayName: Download Manifest Artifacts
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: current
          artifactName: 'manifests'
          itemPattern: '**/*.yaml'
          targetPath: '$(System.ArtifactsDirectory)'
      
      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          connectionType: 'kubernetesServiceConnection'
          kubernetesServiceConnection: 'k8stest-dev-svcconn'
          namespace: 'default'
          manifests: '$(System.ArtifactsDirectory)/deployment.yaml'
          containers: 'snayakwadi41/currency-exchange:${tag}'


